### ISSUE TITLE
Symbol Organizer titles are showing up on artboards

### ISSUE THREAD

**Issue by hvargish** [sonburn/symbol-organizer#107]
![image](https://user-images.githubusercontent.com/15879096/50608324-4f516e80-0e9a-11e9-955b-6d68cb0894b5.png)

**Comment by markDBitHead** [comment]
[Solved] I had the same issue. It turns out I had inadvertently copied the "Titles" group, that this plugin generates, into one of my symbols. This is why I saw the titles in each artboard that contained instances of that particular symbol.

A quick way to find it, assuming you haven't created a lot of groups with "Titles" in the name yourself, is to use the Filter tool at the bottom of the **Layer List panel** and look for a group inside of a symbol where it shouldn't be.

Hope this helps!

**Comment by sonburn** [comment]
@hvargish, @markDBitHead, glad you figured it out. I have a solution in mind to solve this issue. Thanks for your patience, and for using my plugin.
