### ISSUE TITLE
Symbol Organizer doesn't remove symbols

### ISSUE THREAD

**Issue by illustree** [sonburn/symbol-organizer#14]
have a look at the attached Sketch file where there is only one Symbol on the page with one nested symbol ... still the “deleting unused symbols” doesn't work ... that issue is there since the last update I think .. please can you check? Thanks

[symbol organiser issue.sketch.zip](https://github.com/sonburn/symbol-organizer/files/858417/symbol.organiser.issue.sketch.zip)

**Comment by sonburn** [comment]
Thank you for the feedback. This is technically working as designed, because I was being super super uber conservative with deletions, as this functionality gives me the heebie jeebies (I don't want support issues saying I have deleted symbols that shouldn't have been deleted!). That being said, I know of the issue you are referring, and I know I could do better... as of right now any symbol with a nested symbol is considered exempt from deletion. I should run additional process to determine if the symbol with the nested symbol is actually in use, and if not, consider it safe for deletion. I will consider this for future enhancements.

**Comment by illustree** [comment]
hm ... yes you should check if the symbol is used **ONLY on the Symbols Page** (also if it's an override AND only on the Symbols-Page only) --> and if so - just delete it ... actually as it is now the functionality is just not there “remove unused” ... I'm not sure about the complexity of that implementation but that's what would be needed. Thanks in advance

**Comment by sonburn** [comment]
@illustree I just pushed an update to Symbol Organizer (v12.0) which does a much better job of removing unused symbols, as it uses the native isSafeToDelete function of MSSymbolMaster. Please check it out and let me know if you have a better experience!

**Comment by sonburn** [comment]
Although, it seems I found a bug in isSafeToDelete regarding nested nested symbols, which I have reported to Sketch. So in the meantime, I have added back my symbol override protections. It should still be better than it was before!
