### ISSUE TITLE
Symbols not on stage being removed

### ISSUE THREAD

**Issue by illustree** [sonburn/symbol-organizer#4]
currently there is the issue that the plugin removes also symbols which ARE actually used. If I create several icons and create symbols of them #A #B #C. Then create a layout with symbols #A and #B included and create a symbol with nested symbols. Then I would use the sketch inspector and replace the icon #B with #C = The removing “unused” will now remove the #C but actually it is used atm. Please can you add some checking whether a symbol is used by nested-replaced-functionality of sketch? would be so great, thanks!

**Comment by sonburn** [comment]
@illustree, thank you for your feedback.

From my research, if a symbol instance exists of the symbol which contains nested symbols, then those nested symbols register as having instances themselves, and thus will not be removed. Or said another way, a nested symbol will only be removed if the symbol in which it is nested, does not itself have an instance.

It's quirky to say the least, and potentially destructive if you are not paying attention. I debated adding this functionality for these reasons, but ultimately did as it might be useful for some. As an aside, this is the same functionality as found in [Remove Unused Symbols](https://github.com/sketchplugins/remove-unused-symbols), which has the same issue.

All that being said I plan to resolve this issue next, for both nested symbols and overrides (because this is an issue for those as well).

**Comment by sonburn** [comment]
@illustree I believe I have this issue resolved in the latest version. I have added logic to ignore symbols which are nested symbols, which contain  nested symbols, or are used as overrides, when removing unused symbols. Could you please take a look and let me know if you run into any issues.

**Comment by illustree** [comment]
so so cool! many thanks!
