### ISSUE TITLE
Symbols Are All Deleted : Sketch 46.2 Plugin 12.8

### ISSUE THREAD

**Issue by drift3** [sonburn/symbol-organizer#57]
When I run the plugin in Sketch 46.2 with Plugin 12.8 all the symbols are being deleted (this was happening in a previous version, then seemed to be fixed, now it's happening again).

**Comment by sonburn** [comment]
@drift3 This should be technically impossible now, as all symbols are moved on the canvas (never removed). Do you have an example file you would be able to share with me? Are you using Remove Unused Symbols at all?

Otherwise, can you open Sketch and then Console.app (found in Utilities). In the sidebar of Console select '~/Library/Logs', then 'com.bohemiancoding.sketch3'. Run the plugin again, and if there was an error, it should appear in Plugin Output.log. If you could share with me the error, that would help in diagnosing your issue. If there is no error, can you video your experience in Sketch?

**Comment by drift3** [comment]
It seems to be working again with the new update (13.1)... The symbols just move to a different area of the page, which is not a big deal. I just have to zoom out to find them all.

**Comment by sonburn** [comment]
@drift3 The plugin places the first symbol at 0,0 on your canvas, so it _could_ appear everything was deleted if everything simply moved out of your view of the canvas. Hopefully this is all that was happening before; as I said, they can simply NOT be deleted any more as all the plugin does now is move them around (before it used to completely remove and add back in the new position, which burned me in a previous Sketch update).

Glad it's working for you, and thanks for using Symbol Organizer!
